# Generated by Django 5.1.1 on 2024-09-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_availibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='has_size',
            field=models.BooleanField(default=False),
        ),
    ]
