# Generated by Django 5.1.1 on 2024-09-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'contact us message', 'verbose_name_plural': 'contact us messages'},
        ),
    ]
