# Generated by Django 5.1.1 on 2024-09-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
